config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "tasks", to: "tasks#tasks"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"


  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def tasks
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>update Task</h1>

<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_area :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_area :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><strong>Details:</strong> <%= @task.details %></p>
<p><strong>Completed:</strong> <%= @task.completed ? 'Yes' : 'No' %></p>

<%= link_to 'Edit Task', edit_task_path(@task) %>
<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/tasks.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task List</title>
  </head>
  <body>
    <h1>Task List</h1>
      <ul>
        <% @tasks.each do |task| %>
          <li><%= link_to  task.title, task_path(task) %></li>
        <% end %>
      </ul>
    <%= link_to 'New Task', tasks_new_path %>
  </body>
</html>